name: mat281
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=3
  - ipywidgets=7.5.1
  - jupyterlab=1.2.0
  - jupyter_contrib_nbextensions
  - matplotlib=3.3.2
  - nodejs=12.8
  - numpy=1.19.2
  - pandas=1.1.3
  - pandas-profiling=2.3.0
  - pip
  - python=3.7
  - scikit-learn=0.22.1
  - scipy=1.3.1
  - seaborn=0.11.0
  - vega_datasets
  - pip:
    - datachile
    - xmlx
